### PR TITLE
Inline CSS -> External CSS

### LINKED ISSUE #59: Inline CSS -> External CSS
Move all the Inline Styles to an External CSS File.

Note-

- Be careful, nothing should break.
- External CSS File should be created in assets folder.

### PR DESCRIPTION
**Pull request by Cyber-Infernox**
Fixes #59

### CODE REVIEW

**Comment by hackko-20** [comment]
1. remove the TODO as it is not needed in the css file.

**Comment by Cyber-Infernox** [comment]
@hackko-20 
The .gitignore change was due to liveServer port change.
It was in the settings.json file in the .vscode folder.

**Comment by Cyber-Infernox** [comment]
@hackko-20 
I have reverted the .gitignore change now.
And Fixes #59

**Comment by hackko-20** [comment]
1. <style> tag is not used in the CSS file, neither are the {% example %} template tags. Check the code again. Also, test the code on your end before submitting for review.

**Comment by hackko-20** [comment]
@Cyber-Infernox are you working on this PR?

**Comment by Cyber-Infernox** [comment]
@hackko-20 
Yes, I am working on it......I am not able to run this locally.....just figuring it out

**Comment by hackko-20** [comment]
@Cyber-Infernox  Okay, any specific issue you're facing while running this locally?

**Comment by Cyber-Infernox** [comment]
@hackko-20 
Where we have to run the commands for setting up the environment?
It's giving errors when I run it in powershell, git bash and also in python shell.

**Pull request closed without merging**
