### PR TITLE
#71 adding functionality in models

### PR DESCRIPTION
**Pull request by ritishbhardwaj**
Description:

name field in any form must be mandatory and this mention/update will enhance the readability of developer

### CODE REVIEW

**Comment by ritishbhardwaj** [comment]
kindly take a review

**Comment by ritishbhardwaj** [comment]
kindly take look on this PR 
is it good enough to get merge
or if any issues in this , then can we talk

**Comment by DuP-491** [comment]
@ritishbhardwaj  you need to follow proper procedure to get your PR merged into this repository , Closing this PR

**Comment by ritishbhardwaj** [comment]
kindly tell me where to find the steps to get my PR merged into this repository
@DuP-491

**Pull request closed without merging**
