### PR TITLE
Update profile-card.html

### LINKED ISSUE #44: Display Username in Title
In the title bar of the User Profile , display username of user.

This issue is assigned to @Cyber-Infernox

### PR DESCRIPTION
**Pull request by Cyber-Infernox**
Fixes #44 
Displayed username in title.

### CODE REVIEW

**Comment by DuP-491** [comment]
@Cyber-Infernox kindly read issue again

**Comment by Cyber-Infernox** [comment]
@DuP-491 
Fixes #44

**Comment by DuP-491** [comment]
@Cyber-Infernox for userprofile page , title should be Profile {username} , This is dynamic

**Comment by Cyber-Infernox** [comment]
@DuP-491 
Sorry Sir, I shouldn't have taken this issue.
I don,t know about overriding and dynamic website.

**Comment by DuP-491** [comment]
@Cyber-Infernox  are you working on PR?

**Comment by Cyber-Infernox** [comment]
@DuP-491 
Yes Sir, I am trying to figure it out....but I don't know about dynamic websites

**Comment by Cyber-Infernox** [comment]
@DuP-491 
Fixes #44

**Comment by DuP-491** [comment]
@hackko-20

**Review by DuP-491 — APPROVED** [review]

**Comment by DuP-491** [comment]
LGTM! merging

**Pull request merged**
