### PR TITLE
Added filtering using Domain/Subdomain

### LINKED ISSUE #31: Filter Issues by Domain
Filter Issues by Domain - It would be better if you make two choice fields in the model with Domain and Subdomain [Eg: Domain - Web, Subdomain - Django] [There can be multiple subdomains] [Separate tables of Domain and SubDomain can be made for robustness]

This issue is assigned to @kunal2812

### PR DESCRIPTION
**Pull request by kunal2812**
Fixes #31 

image

- Added a foreign key to project model.
- Added functions for filtering in views.py

### CODE REVIEW

**Comment by DuP-491** [comment]
@kunal2812 run lint test using flake8

**Comment by DuP-491** [comment]
image

Subdomain must be optional not compulsory to fill in

**Comment by DuP-491** [comment]
image
It should be clear which domain is selected in UI

**Comment by DuP-491** [comment]
image
Subdomain is not mentioned in issue card

**Comment by DuP-491** [comment]
Currently logic is not working as intended, domain and sub-domain filtering should be working as follows:

1. User can select a specific domain to filter out specific issues.
2. Among above issues they can further filter out issue using sub-domains.

**Comment by DuP-491** [comment]
complete these !! Bonus points incoming good job in fixing Unit Test file :)

**Comment by kunal2812** [comment]
image
- Improved UI and filtering logic
- Made subdomain optional
- Now cards have subdomain mentioned

**Comment by DuP-491** [comment]
image
This is no option to select all again except for going home

**Comment by DuP-491** [comment]
> Currently logic is not working as intended, domain and sub-domain filtering should be working as follows:
> 
> 1. User can select a specific domain to filter out specific issues.
> 2. Among above issues they can further filter out issue using sub-domains.

This has not been fixed as of now

**Comment by kunal2812** [comment]
> > Currently logic is not working as intended, domain and sub-domain filtering should be working as follows:
> > 
> > 1. User can select a specific domain to filter out specific issues.
> > 2. Among above issues they can further filter out issue using sub-domains.
> 
> This has not been fixed as of now

This has been fixed sir, the user can select a domain and then filter those issues in subdomain. Users are also allowed to filter the issues  on the basis of only subdomain.

**Comment by kunal2812** [comment]
> image This is no option to select all again except for going home

I'll fix this.

**Comment by DuP-491** [comment]
LGTM! Merging

**Pull request merged**
