### PR TITLE
create issue from website

### PR DESCRIPTION
**Pull request by prackode**

### CODE REVIEW

**Comment by prackode** [comment]
fixes #34 @hackko-20

**Comment by hackko-20** [comment]
Checking

**Comment by hackko-20** [comment]
Closing it here, as it has some edge cases missing, however accepted it as the issue has been resolved. Would've have opened new issues for the edge cases, but taking time into account it is not possible.

**Comment by prackode** [comment]
will it not be merged into main?

**Comment by hackko-20** [comment]
> will it not be merged into main?

No, without taking every failure case into account we cannot make the code available for everyone to use.

**Pull request closed without merging**
