### PR TITLE
infinite scroll pagination

### PR DESCRIPTION
**Pull request by prackode**

### CODE REVIEW

**Comment by prackode** [comment]
fixes #23 
@DuP-491

**Comment by DuP-491** [comment]
card view and table view are not in sync user can simply go to tabular view to see all issues 
there is no loader animation used pagination loading

**Comment by DuP-491** [comment]
Increase issues par pagination to 6

**Comment by prackode** [comment]
okay I'll make the changes

**Comment by prackode** [comment]
fixed and updated @DuP-491

**Comment by DuP-491** [comment]
checking @prackode

**Comment by DuP-491** [comment]
@prackode still same issue if I shift to tabular view I can see all issues at once while card view is paginated , send in only one set of issues and display them on both tabular and card view

**Pull request closed without merging**
