### PR TITLE
Cyber_Infernox changed the title

### PR DESCRIPTION
**Pull request by Cyber-Infernox**
Changed the title “Current Assignment Requests” to “Your Assignment Requests” on the student’s profile.
(ContriHub-22, Hacktoberfest)

### CODE REVIEW

**Comment by DuP-491** [comment]
@Cyber-Infernox  mention Issue number by writing "Fixes #[Issue Number]"

**Comment by DuP-491** [comment]
@Cyber-Infernox  Reformatting the whole is not required in this issue

**Comment by Cyber-Infernox** [comment]
> @Cyber-Infernox mention Issue number by writing "Fixes #[Issue Number]"

Fixes #27

**Comment by Cyber-Infernox** [comment]
@DuP-491 Fixes #27

**Comment by Cyber-Infernox** [comment]
@DuP-491 I did the reformatting by mistake.
                   I have also solved the issue.

**Comment by DuP-491** [comment]
Checking

**Comment by DuP-491** [comment]
image

@Cyber-Infernox this is breaking , templates are not rendering properly

**Comment by Cyber-Infernox** [comment]
@DuP-491 Fixes #27 
Reverted my earlier changes and then fixed the issue.

**Comment by DuP-491** [comment]
@Cyber-Infernox  Checking

**Comment by DuP-491** [comment]
LGTM! Merging

**Pull request merged**
