### PR TITLE
Fixes #30

### LINKED ISSUE #30: Change the All Project Dropdown in Nav-Bar
Change the All Project Dropdown (from the Homepage of Contrihub) to a modal where project details are displayed in tabular form with name, domain, etc.

### PR DESCRIPTION
**Pull request by kopaljain03**
changes made according to the description in home/home/navbar.html . Now the navbar's all project dropdown is in a tabular model with project name and domain.

### CODE REVIEW

**Comment by hackko-20** [comment]
Please read the issue again. The issue specifies the use of modal. Look for modals in bootstrap to understand what is required.

**Comment by kopaljain03** [comment]
Sir/ma'am sorry for the confusion
can we request for the same issue again ?

**Comment by hackko-20** [comment]
Sorry, you cannot request for the same issue again. This issue has been assigned to someone else. Kindly look for other issues.

**Comment by DuP-491** [comment]
@hackko-20 closing this PR

**Pull request closed without merging**
