### PR TITLE
Implemented Sending Email functionality in separate thread

### PR DESCRIPTION
**Pull request by Krishna1922**

### CODE REVIEW

**Comment by DuP-491** [comment]
@Krishna1922  you have to implement this functionality everywhere not just at one place

**Comment by Krishna1922** [comment]
ok sir after doing I will again do PR

**Comment by Krishna1922** [comment]
@DuP-491 I have done it Sir

**Comment by DuP-491** [comment]
@Krishna1922 checking

**Comment by DuP-491** [comment]
@Krishna1922 delete those commented function rest looks good to me

**Comment by Krishna1922** [comment]
@DuP-491 done sir

**Comment by DuP-491** [comment]
@Krishna1922  Merging

**Pull request merged**
