### PR TITLE
Added Edit Profile Functionality

### LINKED ISSUE #56: Edit Profile Functionality
Implement a functionality where users can edit their profile information.
But here's the catch -

- User's should be able to edit their LinkedIn Profile ID at will, whenever they want.
- However, for editing: Regno, Name, Year, and Course, the user can only submit a request to Admin with updated values.
- For this, the user should be given an option to enter new values, and then an Email should be sent to [contrihub.avishkar@gmail.com](mailto:contrihub.avishkar@gmail.com) stating the Username, User profile link, and updated info of the user.

This issue is currently assigned to @DNA5769

### PR DESCRIPTION
**Pull request by DNA5769**
Fixed #56 

`user_profile/templates/user_profile/profile-card.html`
Here I basically made edit icon which when clicked opens a modal where the user can add his/her/their new profile details. 

`user_profile/templates/user_profile/profile.html`
Here is where all the JS logic for the modal I created earlier resides in. It contains logic of opening and closing modal and even sending requests to the backend. It also does some validating and response messages.

`user_profile/views.py`, `user_profile/urls.py`
Here I created 2 new POST routes namely *profile/user/linkedin_id/edit/* and *profile/user/details/edit/* which deals with editing the linkedin ID and the other details respectively. I thought of using 2 separate routes since both their logics are very different.

`home/helpers.py`, `user_profile/templates/user_profile/mail_template_request_profile_edit.html`
I also made a separate helper function to send the mail to the admin as well as a email template for the mail in case of editing other details. *I just copy pasted both the email helper function and the mail template which was already there and did some changes, huehue*.

### CODE REVIEW

**Comment by DNA5769** [comment]
@DuP-491 Sorry for ping, but I had less time remaining for the issue 😭

**Comment by DuP-491** [comment]
image

@DNA5769 Wrong Year

**Comment by DuP-491** [comment]
image

Remove debug print statement in edit_linkedin_id view function

**Comment by DuP-491** [comment]
@DNA5769  Bonus incoming for handling edge cases :)

**Comment by DNA5769** [comment]
> @DNA5769 Bonus incoming for handling edge cases :)

Edge cases regarding what? 😳

**Comment by DuP-491** [comment]
> > @DNA5769 Bonus incoming for handling edge cases :)
> 
> Edge cases regarding what? 😳

Taking care of status codes and all

**Comment by DuP-491** [comment]
@DNA5769 run linting test

**Comment by DNA5769** [comment]
Thanks Sir, I think since the status code for a successful response is 200, you should reward me 200 bonus points 😅

**Comment by DuP-491** [comment]
image

updating the linkedin in here is not updating the value

**Comment by DNA5769** [comment]
Done Sir

**Comment by DuP-491** [comment]
LGTM! merging

**Pull request merged**
