### PR TITLE
Functionality for Mentor to assign bonus/penalty points and leave remarks while accepting/rejecting the PRs.

### LINKED ISSUE #25: Functionality for Mentor to assign bonus/penalty points and leave remarks while accepting/rejecting the PRs.
Implement Functionality for a mentor to assign bonus/penalty points and leave remarks while accepting/rejecting the PRs. A form will be needed, the model will need the addition of a field for remark.

This issue is currently assigned to @MauryaRitesh

### PR DESCRIPTION
**Pull request by MauryaRitesh**
fixes #25

### CODE REVIEW

**Comment by DuP-491** [comment]
@MauryaRitesh total is not updating according to bonus

**Comment by MauryaRitesh** [comment]
@DuP-491 total score fixed in `rankings.html`

**Comment by DuP-491** [comment]
@MauryaRitesh the change needs to be done in backend , points are the total points of the user
You need to implement this feature such that when accepted bonus are added to the total points

**Comment by DuP-491** [comment]
@MauryaRitesh for every PR request review card, add a drop down button to display the form

**Comment by MauryaRitesh** [comment]
@DuP-491 Done

**Comment by DuP-491** [comment]
@MauryaRitesh  
image

someone added feature to display message instead of http response just add that rest looks good to me

**Pull request merged**
