### PR TITLE
Check Valid LinkedIn Profile Link (#53) resolved

### LINKED ISSUE #2: Bug Navbar
Currently, the Navbar of User Profile Page and Rankings Page is not collapsible i.e. when the screen size is reduced, the buttons disappear.

Make it [collapsible](https://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_navbar_collapse&stacked=h).

### LINKED ISSUE #53: Check Valid LinkedIn Profile Link
Check whether given input linkedin profile is valid or not.
Validity must be checked both on frontend and backend.
Use of regex is encouraged.

This issue is currently assigned to @Umang1103

### PR DESCRIPTION
**Pull request by Umang1103**
Fixes #53 
* Backend: Applied a check on the `complete_profile` and `edit_linkedin_id` for valid linkedin_id using regex.
* Frontend: Displays error message in case of invalid LinkedIn id.

### CODE REVIEW

**Comment by DuP-491** [comment]
@Umang1103  Run lint test

**Comment by Umang1103** [comment]
@DuP-491 Done sir

**Comment by DuP-491** [comment]
@Umang1103  you have mentioned wrong issue number in the description

**Comment by DuP-491** [comment]
@Umang1103 you need to check URL in edit profile functionality on profile page kindly refer to this PR https://github.com/ContriHUB/ContriHUB-22/pull/83

Also the check needs to be implemented on frontend using JS

**Comment by Umang1103** [comment]
Fixed #53
* Implemented the URL check on the edit profile window.
* Error message display done.

**Comment by DuP-491** [comment]
@Umang1103  you need to check for valid linkedin profile in frontend as well

**Comment by DuP-491** [comment]
Closing this PR due to inactivity, will be giving partial points since the check was implemented in the backend

**Pull request merged**
